version: '3.9'

networks:
    menu-parser-app:

services:
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: '${APP_NAME}-server'
        ports:
            - '${APP_PORT}:80'
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
        networks:
            - menu-parser-app
