# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    restaurants:
        veranda:
            name: 'Veranda'
            url: 'https://veranda.bevanda.sk/'
            parser: App\Service\VerandaFoodOptionsParser
        veda:
            name: 'Veda'
            url: 'https://www.store.vedaveg.com/restauracja/veda-vegetarian-vegan-2#menu-denne-menu'
            parser: App\Service\VedaFoodOptionsParser

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $restaurants: '%restaurants%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
